import { jsPDF } from 'jspdf';
import type { Invoice, Customer, Sender } from '../types';
import { getCustomerById, getSenderById } from './mockApi';

export type PDFGenerationMode = 'client' | 'server';

// Configuration for PDF generation mode
let pdfMode: PDFGenerationMode = 'client';

export const setPDFMode = (mode: PDFGenerationMode) => {
  pdfMode = mode;
};

export const getPDFMode = () => pdfMode;

// Client-side PDF generation
const generateClientPDF = (invoice: Invoice): Blob => {
  const doc = new jsPDF();
  const customer = getCustomerById(invoice.customerId);
  const sender = getSenderById(invoice.senderId);

  // Header
  doc.setFontSize(24);
  doc.setTextColor(107, 33, 168);
  doc.text('INVOICE', 105, 25, { align: 'center' });

  // Invoice details
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 150, 45);
  doc.text(`Date: ${new Date(invoice.invoiceDate).toLocaleDateString()}`, 150, 52);
  doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 150, 59);
  doc.text(`Currency: ${invoice.currency}`, 150, 66);

  // Status badge
  const statusColors: Record<string, [number, number, number]> = {
    draft: [107, 114, 128],
    sent: [59, 130, 246],
    paid: [34, 197, 94],
    overdue: [239, 68, 68],
    cancelled: [156, 163, 175],
  };
  const [r, g, b] = statusColors[invoice.status] || [107, 114, 128];
  doc.setFillColor(r, g, b);
  doc.roundedRect(150, 70, 30, 8, 2, 2, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(invoice.status.toUpperCase(), 165, 75, { align: 'center' });

  // From section
  doc.setTextColor(60, 60, 60);
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('From:', 20, 45);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (sender) {
    doc.text(sender.companyName, 20, 52);
    doc.text(sender.contactPerson, 20, 59);
    doc.text(sender.email, 20, 66);
    doc.text(sender.phone, 20, 73);
    const addressLines = sender.address.split(',');
    addressLines.forEach((line, i) => {
      doc.text(line.trim(), 20, 80 + i * 7);
    });
  }

  // To section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 20, 105);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (customer) {
    doc.text(customer.name, 20, 112);
    doc.text(customer.contactPerson, 20, 119);
    doc.text(customer.email, 20, 126);
    doc.text(customer.phone, 20, 133);
    const addressLines = customer.address.split(',');
    addressLines.forEach((line, i) => {
      doc.text(line.trim(), 20, 140 + i * 7);
    });
  }

  // Line items table
  const tableTop = 165;
  doc.setFillColor(107, 33, 168);
  doc.rect(20, tableTop, 170, 10, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Description', 25, tableTop + 7);
  doc.text('Qty', 100, tableTop + 7);
  doc.text('Unit Price', 120, tableTop + 7);
  doc.text('Total', 160, tableTop + 7);

  // Table rows
  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  let y = tableTop + 17;
  invoice.lineItems.forEach((item, index) => {
    if (index % 2 === 0) {
      doc.setFillColor(249, 250, 251);
      doc.rect(20, y - 5, 170, 10, 'F');
    }
    doc.text(item.description, 25, y);
    doc.text(item.quantity.toString(), 100, y);
    doc.text(`${invoice.currency} ${item.unitPrice.toFixed(2)}`, 120, y);
    doc.text(`${invoice.currency} ${item.total.toFixed(2)}`, 160, y);
    y += 10;
  });

  // Summary
  y += 10;
  doc.setDrawColor(200, 200, 200);
  doc.line(120, y, 190, y);
  y += 10;
  
  doc.text('Subtotal:', 130, y);
  doc.text(`${invoice.currency} ${invoice.subtotal.toFixed(2)}`, 160, y);
  y += 8;
  
  doc.text(`Tax (${invoice.taxRate}%):`, 130, y);
  doc.text(`${invoice.currency} ${invoice.taxAmount.toFixed(2)}`, 160, y);
  y += 8;
  
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text('Total:', 130, y);
  doc.text(`${invoice.currency} ${invoice.total.toFixed(2)}`, 160, y);

  // Notes
  if (invoice.notes) {
    y += 20;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Notes:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    const noteLines = doc.splitTextToSize(invoice.notes, 170);
    doc.text(noteLines, 20, y + 7);
  }

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Invoice Builder', 105, 285, { align: 'center' });

  return doc.output('blob');
};

// Mock server-side PDF generation (simulates API call)
const generateServerPDF = async (invoice: Invoice): Promise<Blob> => {
  // Simulate server delay
  await new Promise(resolve => setTimeout(resolve, 500));
  
  // In a real implementation, this would make an API call to the backend
  // For now, we'll use the same client-side generation with a marker
  const doc = new jsPDF();
  const customer = getCustomerById(invoice.customerId);
  const sender = getSenderById(invoice.senderId);

  // Add watermark for server-generated PDF
  doc.setTextColor(230, 230, 230);
  doc.setFontSize(40);
  doc.text('SERVER', 105, 150, { align: 'center', angle: 45 });

  // Header
  doc.setFontSize(24);
  doc.setTextColor(107, 33, 168);
  doc.text('INVOICE', 105, 25, { align: 'center' });

  // Invoice details
  doc.setFontSize(10);
  doc.setTextColor(60, 60, 60);
  
  doc.text(`Invoice #: ${invoice.invoiceNumber}`, 150, 45);
  doc.text(`Date: ${new Date(invoice.invoiceDate).toLocaleDateString()}`, 150, 52);
  doc.text(`Due Date: ${new Date(invoice.dueDate).toLocaleDateString()}`, 150, 59);
  doc.text(`Currency: ${invoice.currency}`, 150, 66);

  // From section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('From:', 20, 45);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (sender) {
    doc.text(sender.companyName, 20, 52);
    doc.text(sender.contactPerson, 20, 59);
    doc.text(sender.email, 20, 66);
    doc.text(sender.phone, 20, 73);
  }

  // To section
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Bill To:', 20, 95);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  if (customer) {
    doc.text(customer.name, 20, 102);
    doc.text(customer.contactPerson, 20, 109);
    doc.text(customer.email, 20, 116);
    doc.text(customer.phone, 20, 123);
  }

  // Line items
  const tableTop = 145;
  doc.setFillColor(107, 33, 168);
  doc.rect(20, tableTop, 170, 10, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.text('Description', 25, tableTop + 7);
  doc.text('Qty', 100, tableTop + 7);
  doc.text('Unit Price', 120, tableTop + 7);
  doc.text('Total', 160, tableTop + 7);

  doc.setTextColor(60, 60, 60);
  doc.setFont('helvetica', 'normal');
  let y = tableTop + 17;
  invoice.lineItems.forEach((item) => {
    doc.text(item.description, 25, y);
    doc.text(item.quantity.toString(), 100, y);
    doc.text(`${invoice.currency} ${item.unitPrice.toFixed(2)}`, 120, y);
    doc.text(`${invoice.currency} ${item.total.toFixed(2)}`, 160, y);
    y += 10;
  });

  // Summary
  y += 10;
  doc.text('Subtotal:', 130, y);
  doc.text(`${invoice.currency} ${invoice.subtotal.toFixed(2)}`, 160, y);
  y += 8;
  doc.text(`Tax (${invoice.taxRate}%):`, 130, y);
  doc.text(`${invoice.currency} ${invoice.taxAmount.toFixed(2)}`, 160, y);
  y += 8;
  doc.setFont('helvetica', 'bold');
  doc.text('Total:', 130, y);
  doc.text(`${invoice.currency} ${invoice.total.toFixed(2)}`, 160, y);

  // Notes
  if (invoice.notes) {
    y += 15;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Notes:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.text(invoice.notes, 20, y + 7);
  }

  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text('Generated by Invoice Builder (Server Mode)', 105, 285, { align: 'center' });

  return doc.output('blob');
};

// Main PDF generation function
export const generateInvoicePDF = async (invoice: Invoice): Promise<Blob> => {
  if (pdfMode === 'server') {
    return generateServerPDF(invoice);
  }
  return generateClientPDF(invoice);
};

// Download PDF
export const downloadInvoicePDF = async (invoice: Invoice, filename?: string) => {
  const blob = await generateInvoicePDF(invoice);
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = filename || `${invoice.invoiceNumber}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
};
